name: CreditCards
main: be\zvz\CreditCards\CreditCards
version: "1.0"

load: STARTUP

author: JellyBrick
api:
- 3.0.0
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11

commands:
 "신용결제":
  description: "신용카드로 결제하는 명령어 입니다."
  usage: "/신용결제 <player> <amount>"
 "신용":
  descipriton: "신용카드 관련 명령어입니다."
  usage: "/신용 <결제금액|도움말|비용납부>"